# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AWS' do
  use_frameworks!

  pod 'Amplify'
  pod 'Amplify/Tools'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'

end
